# 746792098073.dkr.ecr.eu-west-1.amazonaws.com/pandago_saas_php
FROM 746792098073.dkr.ecr.eu-west-1.amazonaws.com/saas_php_base:${PANDA_SAAS_VERSION:-latest}

LABEL 'author'='Fran Lopez <fran.lopez@pandago.eco>'
LABEL 'version'='1.0.1'

WORKDIR /var/www
EXPOSE 9000
CMD ["php-fpm"]
